/*
*	class : CChallenge_GeneralConstants
*	author : Alejandro Esteban	
*	email :
*	fecha : 22/09/2018
*	description: class that store all constants and variable to use in the code
*
*/

public class CChallenge_GeneralConstants {
    
    // Status Code
    public static final String STATUSCODE_OK = 'OK';
    public static final String STATUSCODE_KO = 'KO';
    
    // Response Messages
    public static final String MSG_NO_PARAMS = Label.CChallenge_NoParams;
    public static final String MSG_SUCCESS = Label.CChallenge_Success;
    public static final String MSG_NOVALID_EMAIL = Label.CChallenge_NoValidEmail;
    public static final String MSG_NOVALID_ID = Label.CChallenge_NoValidID;
    public static final String MSG_NO_RESULTS = Label.CChallenge_NoResults;
    public static final String MSG_RESULTS_FOUND = Label.CChallenge_ResultsFound;
    
    // Request and Response
    public static final String REQUEST_CONTENT_TYPE = 'Content-Type';
    public static final String REQUEST_CHARSET_APPLICATION = 'application/json;charset=UTF-8';
}